### ISSUE TITLE
Issue with Markdown parsing when parenthesis embedded in URL

### ISSUE THREAD

**Issue by strangefreeworld** [turtl/desktop#101]
With version 0.6.4 (desktop on Linux), I put a link in to https://en.wikipedia.org/wiki/U.S._national_anthem_protests_(2016%E2%80%93present).  When viewing the note, the closing parenthesis appears as plain text and the link fails to open.

**Comment by orthecreedence** [comment]
This has been fixed in the upcoming v0.7 release!

**Comment by strangefreeworld** [comment]
When will that be released?

**Comment by orthecreedence** [comment]
I really hope in about 3-4 weeks, depending on what happens in my work/personal life.
