### ISSUE TITLE
Linux installer: requierements and icon

### ISSUE THREAD

**Issue by orangemango** [turtl/desktop#15]
The realpath command is needed to run the installation script.

Also the default icon installation fails here.
Maybe because I use a custom icons set: [Elementary+](https://github.com/mank319/elementaryPlus).

I fixed the issue by moving the icon to ~/.local/share/icons.

**Comment by orthecreedence** [comment]
Hello, I've tracked the issue to fix realpath (https://trello.com/c/wA8jxm9O), however the icon is installed in the standard place: `/usr/share/icons/hicolor/128x128/apps/` or `~/.local/share/icons/128x128/apps/`, so not sure why it didn't show up for you. Might have been a theming issue.
