### ISSUE TITLE
Keyboard shortcuts integration

### ISSUE THREAD

**Issue by orangemango** [turtl/desktop#16]
At least search (Ctrl + F) and new note (Ctrl + N) shortcuts.

**Comment by orthecreedence** [comment]
Here are the current shortcuts (undocumented, at the moment):

- `/` while in note view to search notes (`esc` closes the search)
- `x` to clear the current search
- `n` to open "All notes"
- `b` to open "Boards"
- `a` in Boards to add a board
- `a` in Notes to open the add menu
  - `t` to add a text note
  - `f` to add a file note
  - `i` to add an image note
  - `b` to add a bookmark
  - `p` to add a password

Hope this helps!
