### ISSUE TITLE
make clear what boads are selected for a note

### ISSUE THREAD

**Issue by jesrui** [turtl/desktop#18]
Thanks for the app! The first time I added a note to a board, I missed the tick to the right that marks the board as selected. I think putting the tick closer to the board name (to the right) or framing the selected board would give a better visual feedback. See mock-up below.
 
![turtl-sel-frame](https://cloud.githubusercontent.com/assets/6851505/12784389/48a7b3b4-ca87-11e5-94b9-d67f672cd556.png)

**Comment by orthecreedence** [comment]
This is a great idea, thanks for the feedback. In general as I've used the latest version more and more, I've found the board selector in the note editor very clunk and slow (lots of scrolling and looking). I'm going to work on making this better. Tracked here: https://trello.com/c/D8haqWQp
