### ISSUE TITLE
Set window props on Linux

### ISSUE THREAD

**Issue by cadecairos** [turtl/desktop#20]
I use i3wm as my window manager on Linux, and I'd like to assign specific commands to hide/show Turtl, but running `xprop` on the Turtl window reveals no `WM_CLASS` or `WM_NAME` set on the window.

I'm sure there's a way to specify these values somehow :)

**Comment by orthecreedence** [comment]
As a part time i3wm user myself, I love this idea and find it very frustrating when I can't class a window in the config. I'll do my best to figure this out, and luckily testing shouldn't be too hard =]. Tracked here: https://trello.com/c/LMaMcvX3
