### ISSUE TITLE
OS X desktop app will not run without NWJS already present

### ISSUE THREAD

**Issue by nhr** [turtl/desktop#23]
Installed the OS X app cleanly with no warnings, but then the app would just silently fail when I tried to launch it.

I tried to build the package locally, and in doing so I ended up installing NWJS. On a whim I tried running the installed desktop app again, and it magically worked.

My guess is that NWJS needs to be packaged as part of the installation for OS X.

**Comment by orthecreedence** [comment]
This is an odd one. Admittedly I've only tested this on my Mavericks VM, but with a clean install, no previous nw.js, the turtl osx pkg installs and runs fine. For reference, we are packaging nw.js together with the app, so it should have everything it needs to run in the pkg file.

How nice that it failed silently and didn't give an error we could work off of =]. I wonder if it has to do with the way it's being packaged. I don't own a mac so have to do a bunch of weird linux command line junk to generate a pkg file, might have something to do with it.

Can you try wiping the original Turtl install and NWJS and starting from scratch if you have the time?

**Comment by nhr** [comment]
Uninstalled all and then reinstalled from the .pkg file. This time it worked without any problems. Unfortunately I can't be certain that the nwjs uninstall didn't leave some artifacts (environment variables, possibly?) that enabled the second install attempt to work correctly. In any case, problem appears to be solved, so I'll close this out.

**Comment by orthecreedence** [comment]
Thank for trying again, and glad it worked, although it is odd it didn't just work the first time. I'll keep my eye on this one.
