### ISSUE TITLE
Ubuntu 14.04 installation script error

### ISSUE THREAD

**Issue by mikebabb** [turtl/desktop#25]
I installed the realpath package to get around the error detailed in issue #21, but now I get this on running the install script:

```
Copying Turtl to install directory (/opt/turtl)...
cp: cannot overwrite directory ‘/opt/turtl/./turtl’ with non-directory
Error copying Turtl.
```

This was running the script with sudo.

**Comment by orthecreedence** [comment]
Can you `rm -rf /opt/turtl` and try the install script again? That should hopefully get it working for now (but it appears there's another bug in the installer).

Thanks Mike!

**Comment by mikebabb** [comment]
Removing /opt/turtl/ and trying install.sh again has successfully installed Turtl. Thanks!
