### ISSUE TITLE
Constant "problem syncing to the server"

### ISSUE THREAD

**Issue by bbinoy** [turtl/desktop#28]
Hi there, first of all thanks for the great app, keep it going!

I just installed the OSX version and after creating the first note it displays "There was a problem syncing to the server. Trying again soon." at the bottom every few seconds. 

I already restarted the app but didn't help. I checked my internet connection, which is working. And also no firewalls etc. Seems like a bug, or is there a fix for it?

![bildschirmfoto 2016-03-21 um 13 33 19](https://cloud.githubusercontent.com/assets/11409025/13918763/8a42f534-ef69-11e5-8cbb-a9bf688a1838.png)

**Comment by orthecreedence** [comment]
Hey, was an error in the server and should be fixed as of this morning! Thanks for the report.
