### ISSUE TITLE
Better text field scaling in compose note view

### ISSUE THREAD

**Issue by bbinoy** [turtl/desktop#29]
When creating a note with a lot of text, the text input field scales only up to a certain height (approximately half to total available, see attached image). I would find it much more convenient, if it scaled up to the full height of the window. 

But in general I love your apps, thanks!

Using OSX desktop app with the latest turtl version just downloaded from the Website.
![bildschirmfoto 2016-03-21 um 13 32 57](https://cloud.githubusercontent.com/assets/11409025/13918868/3c1d04d4-ef6a-11e5-9268-21d39744f041.png)

**Comment by orthecreedence** [comment]
Yep, this is really obnoxious and has been tracked here: https://trello.com/c/Q3mJc5dB

Thank you for the screens/details when reporting these issues.
