### ISSUE TITLE
nwjs in OSX top navigation bar

### ISSUE THREAD

**Issue by bbinoy** [turtl/desktop#30]
Just a cosmetic issue: It displays nwjs instead of Turtl in the navigation bar on OSX, see attached picture.
![bildschirmfoto 2016-03-21 um 13 41 26](https://cloud.githubusercontent.com/assets/11409025/13919076/a0be5e1e-ef6b-11e5-83b4-edecb8d2a04c.png)

**Comment by orthecreedence** [comment]
Thanks, tracked this: https://trello.com/c/smUJE6pD
