### ISSUE TITLE
Developer ID for mac installer

### ISSUE THREAD

**Issue by dominikwilkowski** [turtl/desktop#32]
Hey guys,

Not sure if the issue goes into this repo but I'm getting below error as the installer isn't signed with a dev ID. Might be worth fixing for easier installs in OSX?

<img width="532" alt="screen shot 2016-04-11 at 5 09 21 pm" src="https://cloud.githubusercontent.com/assets/1266923/14419317/6465ddd6-0008-11e6-8608-ec78f03a62c6.png">

**Comment by orthecreedence** [comment]
Yeah, Apple are real tightwads when it comes to installing software. They want us to pay them money. Which we did recently to start work on the iOS app. So hopefully we can fix this soon. Moving to Trello: https://trello.com/c/8rggPsiR
