### ISSUE TITLE
The 'save' button is labeled 'edit'

### ISSUE THREAD

**Issue by philipashlock** [turtl/desktop#33]
The save button is labeled 'edit' in the main editing interface. I'm accustomed to simplenote based apps that just autosave everything and don't even have an edit or save button, so after I started editing my first note and went back to the main screen I was surprised to see the warning that my note hadn't been saved. Then I was further surprised that there wasn't a save button (the conventional OS keyboard command of command-s is also unavailable).  Eventually I discovered that the save button was labeled "edit" which doesn't make any sense considering you're already in edit mode and to get to the edit mode you click an edit icon. It looks like the button labeled "Edit" not only saves but it also exits out of the editing interface. I would suggest making it so the button only saves and to keep the exit/back functionality to a separate button since this behavior is not intuitive or predictable. Any exit/back button should save as well, but it's important that there's a save button that doesn't exit. The fact that there's no autosave and no keyboard command will make me want to ensure notes are saved frequently without actually exiting the editing interface.

![screen_shot_2016-04-24_at_6_22_55_pm](https://cloud.githubusercontent.com/assets/183402/14770962/37ad9232-0a4b-11e6-8854-50a69bf9b387.png)

**Comment by orthecreedence** [comment]
Good point, this is an easy change. Tracked: https://trello.com/c/SqmSOC0u
