### ISSUE TITLE
Can only log into my profile from the device on which I created the profile

### ISSUE THREAD

**Issue by panditarevolution** [turtl/desktop#37]
I have created a new profile on a device that was behind a vpn. I can log into this profile without an issue from that same device. However logging in doesn't work from any other device.... I tried various ones and it always says "There was a problem with your initial load of your profile. Try again.".

I created another profile behind the same vpn from a different device and the same thing happened.

Then I create a new profile from a device without the vpn and I was able to log into that one from all the other devices.

Is this an IP issue? Any idea what could cause this behaviour?

The devices run cyanogenmod 13, Debian 8 and Debian stretch. The profile was created from Debian stretch.

**Comment by orthecreedence** [comment]
Hi there, this was caused by a package upgrade on our server. The offending
library was fixed and you should be able to log into your accounts now.
Please try again and let me know if you have problems!

Andrew

**Comment by panditarevolution** [comment]
Yes it works now :) Thanks Andrew!
