### ISSUE TITLE
Fixed text box on OSX

### ISSUE THREAD

**Issue by aaronmehar** [turtl/desktop#38]
The height of the text box seems to be fixed, on new and when editing noted. I have one of my screens vertical, and there is a lot of wasted white space, even when the screen is horizontal its the same. The little resize drag button, wont actually drag the box. 

![screen shot 2016-06-11 at 16 11 32](https://cloud.githubusercontent.com/assets/8697411/15985745/4aecf6a2-2fef-11e6-941a-2879f3a720d9.png)

**Comment by orthecreedence** [comment]
This has been fixed (https://trello.com/c/Q3mJc5dB) and is going to go out with the v0.6.4 release (coming this week)! Be on the lookout for the new version!
