### ISSUE TITLE
Constant problem with Syncing 

### ISSUE THREAD

**Issue by samis** [turtl/desktop#44]
Using the Turtl Desktop app 0.6.4 for Linux on openSUSE Tumbleweed, There's a constant popup thing that says: 'There was a problem syncing to the server. Trying again soon.'
I'd attach a backtrace...but I can't find one? Are they just swallowed by something?

**Comment by orthecreedence** [comment]
This seems to happen when a persona gets double-added. Can you send me via email (andrew@turtl.it) the email you used to create your persona? I'll clear out the old one which should let the sync process through. I've got a bugfix coming up in the next version for this so I don't have to manually go fix the database every time =]

**Comment by samis** [comment]
sorry for not getting back to you. Will try again tomorrow
