### ISSUE TITLE
Providing an Arch Linux package

### ISSUE THREAD

**Issue by orschiro** [turtl/desktop#5]
Hi there,

Thanks a lot for developing Turtl! I would love to try it out on my Arch Linux system.

Are there any Arch Linux users here that could share a working PKGBUILD that could be uploaded to the [AUR](https://aur.archlinux.org/)?

Thanks ahead!

**Comment by ChuckDaniels87** [comment]
Now, there is an [AUR package](https://aur.archlinux.org/packages/turtl/). I suppose this issue can be closed. :+1:

**Comment by orschiro** [comment]
@ChuckDaniels87 thanks a lot for your update! :+1:
